import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Onest } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${onest.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
